// <auto-generated />
using System;
using ClassLibrary1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(AirlineContext))]
    partial class AirlineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Assing1.Models.Airplane", b =>
                {
                    b.Property<int>("airplane_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("airplane_companyCompany_id")
                        .HasColumnType("int");

                    b.Property<string>("airplane_models")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("airplane_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_number_of_seats")
                        .HasColumnType("int");

                    b.HasKey("airplane_id");

                    b.HasIndex("airplane_companyCompany_id");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("Week1.Models.Airplane_company", b =>
                {
                    b.Property<int>("Company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Company_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Company_id");

                    b.ToTable("Airplane_companies");
                });

            modelBuilder.Entity("Assing1.Models.Airplane", b =>
                {
                    b.HasOne("Week1.Models.Airplane_company", "airplane_company")
                        .WithMany("Airplanes")
                        .HasForeignKey("airplane_companyCompany_id");

                    b.Navigation("airplane_company");
                });

            modelBuilder.Entity("Week1.Models.Airplane_company", b =>
                {
                    b.Navigation("Airplanes");
                });
#pragma warning restore 612, 618
        }
    }
}
